### ISSUE TITLE
cannot import name 'models' from 'two_factor' (v1.4)

### ISSUE THREAD

**Issue by xmnlab** [jazzband/django-two-factor-auth#522]
After updating django two factor auth to 1.4 I cannot import models anymore.

It seems that the new version doesn't have that file anymore. 

we are using simple-history app and it created a migration that uses `two_factor.models.key_validator`
reading the code, it seems that I need to import it from:

`from two_factor.plugins.phonenumber.models import key_validator`

as it is a breaking change, I wondering if it would be better to be versioned to version 2 instead of 1.4

PS: I am opening this issue just for the record as I didn't find anything in the gh issues

**Comment by claudep** [comment]
Duplicate of #510. It should have been version 2, yes, but now that it was released with version 1.14, what's done is done, sorry.
